language: node_js

node_js:
  - '0.10'

services:
  - mongodb

deploy:
  provider: heroku
  api_key:
    secure: g87qWDXm7YqnF4Uc2yEl4Ln3ts3st54OOoHo7EDHupiaARZrXzfP7R2M2GAv/BV6ZQOH8Op5ie6G8MF7v9SJYlGLAxoqLYH/yHuB/oWZSrCa5CCIPCijm42XJB9ntUQVo4E6WU6v+gDvIxpFerno/mR+RAcwVr0IXqXQsdvNGG0=
  app:
    master: blue-jay
    development: blue-jay-dev
  on:
    repo: bluejay112/robo_betty_alpha

notifications:
  email: false
  slack:
    secure: TKgtzE3PEhWb2cqlQPZEzr/nhyZrftui3Z+G70bXW50NbOMiqD8oOvifQpDzT/a6QxgEMybfmbTz76W7VKmC9PlWW77w/h4lh7A6lBriFRJv72n01c70oTofoRuhI7kqt6S8vIz1wGmiLFPufznaCzMpLuNukqGiJ05PJFap7cI=
